spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample1?createDatabaseifNotExist=true
    username:root
    password:982471826v
    driver-class-name:com.mysql.jdbc.Driver

  jpa:
  hibernate:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl